//
//  Header.h
//  KofaxMobileDemo
//
//  Created by Kofax on 20/03/17.
//  Copyright © 2017 Kofax. All rights reserved.
//

#ifndef Header_h
#define Header_h


#define default_BillPay_IPPString   @"_DoBinarization__DoCropCorrection__DoDocumentDetectorBasedCrop__DoSkewCorrectionAlt__Do90DegreeRotation_4_LoadSetting_<Property Name=\"CSkewDetect.convert_to_gray.Bool\" Value=\"1\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkewDetect.scale_image_down.Bool\" Value=\"1\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkewDetect.scale_down_factor.Int\" Value=\"80\"  Comment=\"DEFAULT  80:60 or  4:3 \" />_LoadSetting_<Property Name=\"CSkewDetect.document_size.Int\" Value=\"2\" Comment=\"MEDIUM, DEFAULT  0\" />_LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value = \"0\"/>"

#define default_CheckDepositFront_IPPString @"_DeviceType_2__DoSkewCorrectionPage__DoCropCorrection__Do90DegreeRotation_9_DoScaleImageToDPI_200_DoFindTextHP__ProcessCheckFront__DoBinarization__LoadInlineSetting_[CSkewDetect.convert_to_gray.Bool=1]__LoadInlineSetting_[CSkewDetect.scale_image_down.Bool=1]_LoadInlineSetting_[CSkewDetect.scale_down_factor.Int=80]_LoadInlineSetting_[CSkewDetect.correct_illumination.Bool=0]"

#define default_CheckDepositLoadLine @"__LoadInlineSetting_[CSkewDetect.convert_to_gray.Bool=1]_LoadInlineSetting_[CSkewDetect.scale_image_down.Bool=1]_LoadInlineSetting_[CSkewDetect.scale_down_factor.Int=80]_LoadInlineSetting_[CSkewDetect.correct_illumination.Bool=0]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercX1.Int=4]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercX2.Int=96]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercY1.Int=4]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercY2.Int=96]_LoadInlineSetting_[CBinarize.Contrast_Slider_Pos.Int=4]_LoadInlineSetting_[CBinarize.Cleanup_Slider_Pos.Int=4]"

#define default_CreditCard_IPPString @"_DeviceType_2_Do90DegreeRotation_4_DoCropCorrection__DoScaleImageToDPI_300_DoSkewCorrectionPage__DocDimLarge_3.375_DocDimSmall_2.125_LoadInlineSetting_[CSkewDetect.correct_illumination.Bool=0]_LoadInlineSetting_[CSkewDetect.double_bkg_check_variability_thr.Int=-1]_LoadInlineSetting_[CSkewDetect.color_stats_error_sum_thr_white_bkg=24]"

#define default_CustomComponent_IPPString @"_DoColor__DoCropCorrection__DoSkewCorrectionPage__Do90DegreeRotation_4_DoScaleImageToDPI_200"

#define default_Passport_IPPString @"_DeviceType_2__DoCropCorrection__DoSkewCorrectionAlt__Do90DegreeRotation_4_DoScaleImageToDPI_300_DocDimSmall_3.465_DocDimLarge_4.921_"

//CSKEW String
#define BillPay_Convert_To_Gray_SKEW_String @"_LoadSetting_<Property Name=\"CSkewDetect.convert_to_gray.Bool\" Value=\"%d\" Comment=\"DEFAULT 0 \" />"

#define BillPay_CSKEW_String @"_LoadSetting_<Property Name=\"CSkewDetect.scale_image_down.Bool\" Value=\"1\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkewDetect.scale_down_factor.Int\" Value=\"80\"  Comment=\"DEFAULT  80:60 or  4:3 \" />_LoadSetting_<Property Name=\"CSkewDetect.document_size.Int\" Value=\"2\" Comment=\"MEDIUM, DEFAULT  0\" />_LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value = \"0\"/>"

#define CreditCard_CSKEW_String  @"LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value=\"0\" />_LoadSetting_<Property Name=\"CSkewDetect.Remove_Shadows\" Value=\"0\" />_LoadSetting_<Property Name=\"CSkewDetect.color_stats_error_sum_thr_white_bkg\" Value=\"36\" />_LoadSetting_<Property Name=\"CSkewDetect.step_white_bkg\" Value=\"16\" />_LoadSetting_<Property Name=\"CSkewDetect.bright_window\" Value=\"255\" />_LoadSetting_<Property Name=\"EdgeCleanup.enable\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.PerformRecognition\" Value=\"1\" />_LoadSetting_<Property Name=\"CZoneExtract.Enable\" Value=\"1\" />_LoadSetting_<Property Name=\"CZoneExtract.UseFieldType\" Value=\"2\" />_LoadSetting_<Property Name=\"CZoneExtract.NumZones\" Value=\"1\" />_LoadSetting_<Property Name=\"CZoneExtract.AspectRatio.Double\" Value=\"1.584112\" />_LoadSetting_<Property Name=\"CZoneExtract.LineLabels.00.00.String\" Value=\"DLNumber\" />_LoadSetting_<Property Name=\"CZoneExtract.LineLabelsTemplate.00.00.String\" Value=\"1:9999[0-9 ]\" />_LoadSetting_<Property Name=\"CZoneExtract.Max_bbX1.00.Int\" Value=\"843\" />_LoadSetting_<Property Name=\"CZoneExtract.Max_bbY1.00.Int\" Value=\"5000\" />_LoadSetting_<Property Name=\"CZoneExtract.Max_bbX2.00.Int\" Value=\"9500\" />_LoadSetting_<Property Name=\"CZoneExtract.Max_bbY2.00.Int\" Value=\"6954\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_bbX1.00.Int\" Value=\"931\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_bbY1.00.Int\" Value=\"5503\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_bbX2.00.Int\" Value=\"9068\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_bbY2.00.Int\" Value=\"6463\" />_LoadSetting_<Property Name=\"CZoneExtract.Intermittent.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.Invert.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.LineHeight.00.00.Int\" Value=\"961\" />_LoadSetting_<Property Name=\"CZoneExtract.LineWidth.00.00.Int\" Value=\"8396\" />_LoadSetting_<Property Name=\"CZoneExtract.LineMedianX1.00.00.Int\" Value=\"1058\" />_LoadSetting_<Property Name=\"CZoneExtract.LineMedianX2.00.00.Int\" Value=\"9010\" />_LoadSetting_<Property Name=\"CZoneExtract.LineMedianY1.00.00.Int\" Value=\"5504\" />_LoadSetting_<Property Name=\"CZoneExtract.LineMedianY2.00.00.Int\" Value=\"6478\" />_LoadSetting_<Property Name=\"CZoneExtract.Penalty_Coe.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_Delta_RG.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_Delta_RB.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.Median_Delta_GB.00.Int\" Value=\"0\" />_LoadSetting_<Property Name=\"CZoneExtract.Binarization_Method.00.Int\" Value=\"3\" />"

#define CD_Convert_To_Gray_SKEW_String @"_LoadSetting_<Property Name=\"CSkewDetect.convert_to_gray.Bool\" Value=\"%d\" Comment=\"DEFAULT 0 \" />"

#define CD_SKEW_String @"_DeviceType_2__LoadSetting_<Property Name=\"CSkewDetect.scale_image_down.Bool\" Value=\"1\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkewDetect.scale_down_factor.Int\" Value=\"80\"  Comment=\"DEFAULT  80:60 or  4:3 \" />_LoadSetting_<Property Name=\"CSkewDetect.document_size.Int\" Value=\"2\" Comment=\"MEDIUM, DEFAULT  0\" />_LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value = \"0\"/>"

#define CD_Front_CSKEW_String @"_LoadInlineSetting_<Property Name=\"CDetectMpHp.RegionOfInterestPercX1.Int\" Value=\"50\" Comment=\"DEFAULT 10 \" />_LoadInlineSetting_<Property Name=\"CDetectMpHp.RegionOfInterestPercX2.Int\" Value=\"95\" Comment=\"DEFAULT 90 \" />_LoadInlineSetting_<Property Name=\"CDetectMpHp.RegionOfInterestPercY1.Int\" Value=\"60\" Comment=\"DEFAULT 50 \" />_LoadInlineSetting_<Property Name=\"CDetectMpHp.RegionOfInterestPercY2.Int\" Value=\"90\" Comment=\"DEFAULT 80 \" />_LoadInlineSetting_<Property Name=\"CBinarize.Contrast_Slider_Pos.Int\" Value=\"4\" Comment=\"DEFAULT 10 \" />_LoadInlineSetting_<Property Name=\"CBinarize.Cleanup_Slider_Pos.Int\" Value=\"4\" Comment=\"DEFAULT 10 \" />"

#define CD_Back_CSKEW_String @"_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercX2.Int=96]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercY1.Int=4]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercY2.Int=96]_LoadInlineSetting_[CBinarize.Contrast_Slider_Pos.Int=4]_LoadInlineSetting_[CBinarize.Cleanup_Slider_Pos.Int=4]_LoadInlineSetting_[CDetectMpHp.RegionOfInterestPercX1.Int=4]"

#define default_DL_LoadLine_String  @"_LoadSetting_<Property Name=\"CSkewDetect.prorate_error_sum_thr_bkg_brightness.Bool\" Value=\"1\" Comment=\"DEFAULT 0\" />_LoadSetting_<Property Name=\"CSkwCor.Do_Fast_Rotation.Bool\" Value=\"0\" Comment=\"DEFAULT 1\" />_LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value=\"0\" Comment=\"DEFAULT 1\" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Scanner_Bkg.Bool\" Value=\"0\" Comment=\"DEFAULT 1 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Red.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Green.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Blue.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />"
#define default_DL_CSKEW_String @"_LoadSetting_<Property Name=\"CSkewDetect.prorate_error_sum_thr_bkg_brightness.Bool\" Value=\"1\" Comment=\"DEFAULT 0\" />_LoadSetting_<Property Name=\"CSkwCor.Do_Fast_Rotation.Bool\" Value=\"0\" Comment=\"DEFAULT 1\" />_LoadSetting_<Property Name=\"CSkewDetect.correct_illumination.Bool\" Value=\"0\" Comment=\"DEFAULT 1\" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Scanner_Bkg.Bool\" Value=\"0\" Comment=\"DEFAULT 1 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Red.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Green.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />_LoadSetting_<Property Name=\"CSkwCor.Fill_Color_Blue.Byte\" Value=\"255\" Comment=\"DEFAULT 0 \" />"
#define default_CC_LoadLIneSettings @"_LoadInlineSetting_[CSkewDetect.correct_illumination.Bool=0]_LoadInlineSetting_[CSkewDetect.double_bkg_check_variability_thr.Int=-1]_LoadInlineSetting_[CSkewDetect.color_stats_error_sum_thr_white_bkg=24]"

#endif /* Header_h */
